Multiple errors that need fixing.
NullReferenceException: Object reference not set to an instance of an object
PathFinder.BreadthFirstSearch () (at Assets/Scripts/PathFinder.cs:74)
PathFinder.GetNewPath () (at Assets/Scripts/PathFinder.cs:125)
EnemyController.FindPath () (at Assets/Scripts/EnemyController.cs:66)
EnemyController.OnEnable () (at Assets/Scripts/EnemyController.cs:25)
UnityEngine.Object:Instantiate(GameObject, Transform)
ObjectPool:PopulatePool() (at Assets/Scripts/ObjectPool.cs:44)
ObjectPool:Awake() (at Assets/Scripts/ObjectPool.cs:15)

SerializedObjectNotCreatableException: Object at index 0 is null
UnityEditor.Editor.CreateSerializedObject () (at /Users/bokken/build/output/unity/unity/Editor/Mono/Inspector/Editor.cs:717)
UnityEditor.Editor.GetSerializedObjectInternal () (at /Users/bokken/build/output/unity/unity/Editor/Mono/Inspector/Editor.cs:689)
UnityEditor.Editor.get_serializedObject () (at /Users/bokken/build/output/unity/unity/Editor/Mono/Inspector/Editor.cs:583)
UnityEditor.TransformInspector.OnEnable () (at /Users/bokken/build/output/unity/unity/Editor/Mono/Inspector/TransformInspector.cs:26)